POST http://localhost:5243/timeblock
Content-Type: application/json

{
    "Name": "Programming",
    "Location": "Sheffield",
    "StartTime": "2025-04-08T12:00:00.000Z",
    "EndTime": "2025-04-08T15:00:00.000Z"
}
###

POST http://localhost:5243/timeblock
Content-Type: application/json

{
    "Name": "Gym",
    "Location": "Sheffield",
    "StartTime": "2025-03-01T09:00:00.000Z",
    "EndTime": "2025-03-01T11:00:00.000Z"
}
###
PATCH http://localhost:5243/timeblock/1
Content-Type: application/json

{
    "Name": "Running",
    "EndTime": "2025-04-01T18:00:00.000Z"
}
###

DELETE http://localhost:5243/timeblock/4
###
GET http://localhost:5243/timeblock
###
POST http://localhost:5243/register
Content-Type: application/json

{
  "email": "camjr246@yahoo.co.uk",
  "password": "zxcCXZ2003#"
}

###
POST http://localhost:5243/forge
Content-Type: application/json

{
    "message": "Date with Sam next Tuesday at Rajput from 7-8"
}